version: '3.8'

services:
  #nginx
  server:
    container_name: nginx
    image: nginx:latest
    restart: on-failure
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  #php
  app:
    container_name: app
    build:
      dockerfile: ./config/php/Dockerfile
    restart: on-failure
    volumes:
      - ./app:/var/www/html
    depends_on: [ server ]
